import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossOrigin="anonymous"></link>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container border border-2 mt-3">
          <div className="row border border-2">
          <Link href="/" className="col border border-2" style={{textDecoration:"none"}}>HOME</Link>
          <Link href="/Contact" className="col border border-2" style={{textDecoration:"none"}}>CONTACT</Link>
          <Link href="/ABOUT" className="col border border-2" style={{textDecoration:"none"}}>ABOUT</Link>
        </div>
        <div className="row border border-2" style={{height:"500px"}}>
          <div className="col-2 border border-2">Sidebar</div>
          <div className="col">{children}</div>
        </div>
        
        <div className="row border border-2"><p className="text-center">Footer</p></div>
        </div>
        
      </body>
    </html>
  );
}
